name: tech_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  rxdart: ^0.24.1
  equatable: ^1.2.2
  dio: ^3.0.9
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
